import { IUser } from "../types/user";

export const mockUsers: IUser[] = [
  {
    userName: "JohnDoe",
    email: "johndoe@example.com",
    age: 28,
    phone: "123-456-7890",
    address: "123 Main St, Springfield",
    status: "active",
  },
  {
    userName: "JaneSmith",
    email: "janesmith@example.com",
    age: 34,
    phone: "234-567-8901",
    address: "456 Oak St, Shelbyville",
    status: "inactive",
  },
  {
    userName: "AliceBrown",
    email: "alicebrown@example.com",
    age: 22,
    phone: "345-678-9012",
    address: "789 Pine St, Capital City",
    status: "active",
  },
  {
    userName: "BobJohnson",
    email: "bobjohnson@example.com",
    age: 45,
    phone: "456-789-0123",
    address: "101 Maple St, Ogdenville",
    status: "inactive",
  },
  {
    userName: "CharlieWhite",
    email: "charliewhite@example.com",
    age: 38,
    phone: "567-890-1234",
    address: "202 Birch St, North Haverbrook",
    status: "active",
  },
  {
    userName: "DavidGreen",
    email: "davidgreen@example.com",
    age: 26,
    phone: "678-901-2345",
    address: "303 Cedar St, Springfield",
    status: "active",
  },
  {
    userName: "EmilyBlack",
    email: "emilyblack@example.com",
    age: 31,
    phone: "789-012-3456",
    address: "404 Elm St, Brockway",
    status: "inactive",
  },
  {
    userName: "FrankYellow",
    email: "frankyellow@example.com",
    age: 29,
    phone: "890-123-4567",
    address: "505 Fir St, Springfield",
    status: "active",
  },
  {
    userName: "GracePink",
    email: "gracepink@example.com",
    age: 40,
    phone: "901-234-5678",
    address: "606 Maple St, Springfield",
    status: "inactive",
  },
  {
    userName: "HenryBlue",
    email: "henryblue@example.com",
    age: 50,
    phone: "012-345-6789",
    address: "707 Cedar St, Capital City",
    status: "active",
  },
];
