import { IUser } from "../types/user";

export const mockUsers: IUser[] = [
  {
    userName: "JohnDoe",
    email: "johndoe@example.com",
    age: 28,
    phone: "123-456-7890",
    address: {
      country: "USA",
      city: "Springfield",
      region: "Illinois",
      street: "Main St",
      postalCode: "62701",
      isPrimary: true,
      houseNumber: "123",
    },
    status: "active",
  },
  {
    userName: "JaneSmith",
    email: "janesmith@example.com",
    age: 34,
    phone: "234-567-8901",
    address: {
      country: "USA",
      city: "Shelbyville",
      region: "Kentucky",
      street: "Oak St",
      postalCode: "40065",
      isPrimary: true,
      houseNumber: "456",
    },
    status: "inactive",
  },
  {
    userName: "AliceBrown",
    email: "alicebrown@example.com",
    age: 22,
    phone: "345-678-9012",
    address: {
      country: "USA",
      city: "Capital City",
      region: "California",
      street: "Pine St",
      postalCode: "90001",
      isPrimary: true,
      houseNumber: "789",
    },
    status: "active",
  },
  {
    userName: "BobJohnson",
    email: "bobjohnson@example.com",
    age: 45,
    phone: "456-789-0123",
    address: {
      country: "USA",
      city: "Ogdenville",
      region: "Ohio",
      street: "Maple St",
      postalCode: "44101",
      isPrimary: true,
      houseNumber: "101",
    },
    status: "inactive",
  },
  {
    userName: "CharlieWhite",
    email: "charliewhite@example.com",
    age: 38,
    phone: "567-890-1234",
    address: {
      country: "USA",
      city: "North Haverbrook",
      region: "New Jersey",
      street: "Birch St",
      postalCode: "07001",
      isPrimary: true,
      houseNumber: "202",
    },
    status: "active",
  },
  {
    userName: "DavidGreen",
    email: "davidgreen@example.com",
    age: 26,
    phone: "678-901-2345",
    address: {
      country: "USA",
      city: "Springfield",
      region: "Missouri",
      street: "Cedar St",
      postalCode: "65801",
      isPrimary: true,
      houseNumber: "303",
    },
    status: "active",
  },
  {
    userName: "EmilyBlack",
    email: "emilyblack@example.com",
    age: 31,
    phone: "789-012-3456",
    address: {
      country: "USA",
      city: "Brockway",
      region: "Michigan",
      street: "Elm St",
      postalCode: "49501",
      isPrimary: true,
      houseNumber: "404",
    },
    status: "inactive",
  },
  {
    userName: "FrankYellow",
    email: "frankyellow@example.com",
    age: 29,
    phone: "890-123-4567",
    address: {
      country: "USA",
      city: "Springfield",
      region: "Oregon",
      street: "Fir St",
      postalCode: "97401",
      isPrimary: true,
      houseNumber: "505",
    },
    status: "active",
  },
  {
    userName: "GracePink",
    email: "gracepink@example.com",
    age: 40,
    phone: "901-234-5678",
    address: {
      country: "USA",
      city: "Springfield",
      region: "Massachusetts",
      street: "Maple St",
      postalCode: "01101",
      isPrimary: true,
      houseNumber: "606",
    },
    status: "inactive",
  },
  {
    userName: "HenryBlue",
    email: "henryblue@example.com",
    age: 50,
    phone: "012-345-6789",
    address: {
      country: "USA",
      city: "Capital City",
      region: "Texas",
      street: "Cedar St",
      postalCode: "73301",
      isPrimary: true,
      houseNumber: "707",
    },
    status: "active",
  },
];
